### ISSUE TITLE
DS0001 ed6: feature names should have a single default

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#86]
* Only one `featureName` should be marked as the default. These features have many names marked as the default
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/e65885a4-058b-4405-9368-d8538ced59d1)

**Comment by kusala9** [comment]
I Saw this too. Encoding error.

**Comment by kusala9** [comment]
should be fixed in edition 7 of DS1.

**Comment by DavidGrant-NIWC** [comment]
Problem is still present on at least one feature. I'll add a validation check to the viewer to automate detection of these issues.
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/8a702072-b819-4123-9b25-7eb4564ad3e2)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/0642b9dd-a38a-4285-ad70-2beb2e83db31)

**Comment by kusala9** [comment]
I'll take a look in the morning and see whuch ones are still invalid. We don't validate on these but we could write a check..

**Comment by kusala9** [comment]
https://github.com/iho-ohi/S-101-Test-Datasets/commit/163f17fd6ea35fbff313b47457a12e9bfdef2724 should do it.... try now.

**Comment by DavidGrant-NIWC** [comment]
It's fixed in edition 2 of edition 7 :-)
